(cl:defpackage test_rospy-msg
  (:use )
  (:export
   "<FLOATS>"
   "FLOATS"
   "<PYTHONKEYWORD>"
   "PYTHONKEYWORD"
   "<TESTCONSTANTS>"
   "TESTCONSTANTS"
   "<HEADERHEADERVAL>"
   "HEADERHEADERVAL"
   "<TESTFIXEDARRAY>"
   "TESTFIXEDARRAY"
   "<ARRAYVAL>"
   "ARRAYVAL"
   "<EMBEDTEST>"
   "EMBEDTEST"
   "<TRANSITIVEIMPORT>"
   "TRANSITIVEIMPORT"
   "<HEADERVAL>"
   "HEADERVAL"
   "<VAL>"
   "VAL"
   "<TRANSITIVEMSG1>"
   "TRANSITIVEMSG1"
   "<TRANSITIVEMSG2>"
   "TRANSITIVEMSG2"
  ))

