/* Auto-generated by genmsg_cpp for file /home/julian/aaad/interactive-manipulation-sandbox/binfrastructure/ros/src/executer_actions/msg/ExecuteActionGoal.msg */
#ifndef EXECUTER_ACTIONS_MESSAGE_EXECUTEACTIONGOAL_H
#define EXECUTER_ACTIONS_MESSAGE_EXECUTEACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "executer_actions/ExecuteGoal.h"

namespace executer_actions
{
template <class ContainerAllocator>
struct ExecuteActionGoal_ {
  typedef ExecuteActionGoal_<ContainerAllocator> Type;

  ExecuteActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  ExecuteActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::executer_actions::ExecuteGoal_<ContainerAllocator>  _goal_type;
   ::executer_actions::ExecuteGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::executer_actions::ExecuteActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ExecuteActionGoal
typedef  ::executer_actions::ExecuteActionGoal_<std::allocator<void> > ExecuteActionGoal;

typedef boost::shared_ptr< ::executer_actions::ExecuteActionGoal> ExecuteActionGoalPtr;
typedef boost::shared_ptr< ::executer_actions::ExecuteActionGoal const> ExecuteActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::executer_actions::ExecuteActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace executer_actions

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::executer_actions::ExecuteActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "decf5be1834dfd04fda2b6d4ef9fbdb4";
  }

  static const char* value(const  ::executer_actions::ExecuteActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdecf5be1834dfd04ULL;
  static const uint64_t static_value2 = 0xfda2b6d4ef9fbdb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "executer_actions/ExecuteActionGoal";
  }

  static const char* value(const  ::executer_actions::ExecuteActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
ExecuteGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: executer_actions/ExecuteGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# JSON encoded action to execute\n\
string action\n\
\n\
\n\
";
  }

  static const char* value(const  ::executer_actions::ExecuteActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::executer_actions::ExecuteActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ExecuteActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::executer_actions::ExecuteActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::executer_actions::ExecuteActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::executer_actions::ExecuteGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // EXECUTER_ACTIONS_MESSAGE_EXECUTEACTIONGOAL_H

