; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude EvaluateQueryGoal.msg.html

(cl:defclass <EvaluateQueryGoal> (roslisp-msg-protocol:ros-message)
  ((query
    :reader query
    :initarg :query
    :type activity_msgs-msg:Query
    :initform (cl:make-instance 'activity_msgs-msg:Query)))
)

(cl:defclass EvaluateQueryGoal (<EvaluateQueryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EvaluateQueryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EvaluateQueryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<EvaluateQueryGoal> is deprecated: use activity_msgs-msg:EvaluateQueryGoal instead.")))

(cl:ensure-generic-function 'query-val :lambda-list '(m))
(cl:defmethod query-val ((m <EvaluateQueryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:query-val is deprecated.  Use activity_msgs-msg:query instead.")
  (query m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EvaluateQueryGoal>) ostream)
  "Serializes a message object of type '<EvaluateQueryGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'query) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EvaluateQueryGoal>) istream)
  "Deserializes a message object of type '<EvaluateQueryGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'query) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EvaluateQueryGoal>)))
  "Returns string type for a message object of type '<EvaluateQueryGoal>"
  "activity_msgs/EvaluateQueryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EvaluateQueryGoal)))
  "Returns string type for a message object of type 'EvaluateQueryGoal"
  "activity_msgs/EvaluateQueryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EvaluateQueryGoal>)))
  "Returns md5sum for a message object of type '<EvaluateQueryGoal>"
  "f06b9b6920756d3c47a891fd8eed561f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EvaluateQueryGoal)))
  "Returns md5sum for a message object of type 'EvaluateQueryGoal"
  "f06b9b6920756d3c47a891fd8eed561f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EvaluateQueryGoal>)))
  "Returns full string definition for message of type '<EvaluateQueryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%Query query~%~%~%================================================================================~%MSG: activity_msgs/Query~%string query~%QueryArg[] args~%~%================================================================================~%MSG: activity_msgs/QueryArg~%string name~%~%# JSON encoded value~%string value~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EvaluateQueryGoal)))
  "Returns full string definition for message of type 'EvaluateQueryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%Query query~%~%~%================================================================================~%MSG: activity_msgs/Query~%string query~%QueryArg[] args~%~%================================================================================~%MSG: activity_msgs/QueryArg~%string name~%~%# JSON encoded value~%string value~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EvaluateQueryGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'query))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EvaluateQueryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'EvaluateQueryGoal
    (cl:cons ':query (query msg))
))
