; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude EvaluateQueryFeedback.msg.html

(cl:defclass <EvaluateQueryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass EvaluateQueryFeedback (<EvaluateQueryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <EvaluateQueryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'EvaluateQueryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<EvaluateQueryFeedback> is deprecated: use activity_msgs-msg:EvaluateQueryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <EvaluateQueryFeedback>) ostream)
  "Serializes a message object of type '<EvaluateQueryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <EvaluateQueryFeedback>) istream)
  "Deserializes a message object of type '<EvaluateQueryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<EvaluateQueryFeedback>)))
  "Returns string type for a message object of type '<EvaluateQueryFeedback>"
  "activity_msgs/EvaluateQueryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'EvaluateQueryFeedback)))
  "Returns string type for a message object of type 'EvaluateQueryFeedback"
  "activity_msgs/EvaluateQueryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<EvaluateQueryFeedback>)))
  "Returns md5sum for a message object of type '<EvaluateQueryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'EvaluateQueryFeedback)))
  "Returns md5sum for a message object of type 'EvaluateQueryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<EvaluateQueryFeedback>)))
  "Returns full string definition for message of type '<EvaluateQueryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# No feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'EvaluateQueryFeedback)))
  "Returns full string definition for message of type 'EvaluateQueryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# No feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <EvaluateQueryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <EvaluateQueryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'EvaluateQueryFeedback
))
