; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude ExecuteFeedback.msg.html

(cl:defclass <ExecuteFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ExecuteFeedback (<ExecuteFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<ExecuteFeedback> is deprecated: use activity_msgs-msg:ExecuteFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteFeedback>) ostream)
  "Serializes a message object of type '<ExecuteFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteFeedback>) istream)
  "Deserializes a message object of type '<ExecuteFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteFeedback>)))
  "Returns string type for a message object of type '<ExecuteFeedback>"
  "activity_msgs/ExecuteFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteFeedback)))
  "Returns string type for a message object of type 'ExecuteFeedback"
  "activity_msgs/ExecuteFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteFeedback>)))
  "Returns md5sum for a message object of type '<ExecuteFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteFeedback)))
  "Returns md5sum for a message object of type 'ExecuteFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteFeedback>)))
  "Returns full string definition for message of type '<ExecuteFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteFeedback)))
  "Returns full string definition for message of type 'ExecuteFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteFeedback
))
