; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude ListRunningActivitiesFeedback.msg.html

(cl:defclass <ListRunningActivitiesFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ListRunningActivitiesFeedback (<ListRunningActivitiesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ListRunningActivitiesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ListRunningActivitiesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<ListRunningActivitiesFeedback> is deprecated: use activity_msgs-msg:ListRunningActivitiesFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ListRunningActivitiesFeedback>) ostream)
  "Serializes a message object of type '<ListRunningActivitiesFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ListRunningActivitiesFeedback>) istream)
  "Deserializes a message object of type '<ListRunningActivitiesFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ListRunningActivitiesFeedback>)))
  "Returns string type for a message object of type '<ListRunningActivitiesFeedback>"
  "activity_msgs/ListRunningActivitiesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ListRunningActivitiesFeedback)))
  "Returns string type for a message object of type 'ListRunningActivitiesFeedback"
  "activity_msgs/ListRunningActivitiesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ListRunningActivitiesFeedback>)))
  "Returns md5sum for a message object of type '<ListRunningActivitiesFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ListRunningActivitiesFeedback)))
  "Returns md5sum for a message object of type 'ListRunningActivitiesFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ListRunningActivitiesFeedback>)))
  "Returns full string definition for message of type '<ListRunningActivitiesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# empty feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ListRunningActivitiesFeedback)))
  "Returns full string definition for message of type 'ListRunningActivitiesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# empty feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ListRunningActivitiesFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ListRunningActivitiesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ListRunningActivitiesFeedback
))
