; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude ListRunningActivitiesResult.msg.html

(cl:defclass <ListRunningActivitiesResult> (roslisp-msg-protocol:ros-message)
  ((running_activities
    :reader running_activities
    :initarg :running_activities
    :type (cl:vector activity_msgs-msg:RunningActivityInfo)
   :initform (cl:make-array 0 :element-type 'activity_msgs-msg:RunningActivityInfo :initial-element (cl:make-instance 'activity_msgs-msg:RunningActivityInfo))))
)

(cl:defclass ListRunningActivitiesResult (<ListRunningActivitiesResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ListRunningActivitiesResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ListRunningActivitiesResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<ListRunningActivitiesResult> is deprecated: use activity_msgs-msg:ListRunningActivitiesResult instead.")))

(cl:ensure-generic-function 'running_activities-val :lambda-list '(m))
(cl:defmethod running_activities-val ((m <ListRunningActivitiesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:running_activities-val is deprecated.  Use activity_msgs-msg:running_activities instead.")
  (running_activities m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ListRunningActivitiesResult>) ostream)
  "Serializes a message object of type '<ListRunningActivitiesResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'running_activities))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'running_activities))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ListRunningActivitiesResult>) istream)
  "Deserializes a message object of type '<ListRunningActivitiesResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'running_activities) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'running_activities)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'activity_msgs-msg:RunningActivityInfo))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ListRunningActivitiesResult>)))
  "Returns string type for a message object of type '<ListRunningActivitiesResult>"
  "activity_msgs/ListRunningActivitiesResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ListRunningActivitiesResult)))
  "Returns string type for a message object of type 'ListRunningActivitiesResult"
  "activity_msgs/ListRunningActivitiesResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ListRunningActivitiesResult>)))
  "Returns md5sum for a message object of type '<ListRunningActivitiesResult>"
  "3611cca087931f599cd9f9c453d0edd4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ListRunningActivitiesResult)))
  "Returns md5sum for a message object of type 'ListRunningActivitiesResult"
  "3611cca087931f599cd9f9c453d0edd4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ListRunningActivitiesResult>)))
  "Returns full string definition for message of type '<ListRunningActivitiesResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%RunningActivityInfo[] running_activities~%~%~%================================================================================~%MSG: activity_msgs/RunningActivityInfo~%string activity_type~%uint64 activity_id~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ListRunningActivitiesResult)))
  "Returns full string definition for message of type 'ListRunningActivitiesResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%RunningActivityInfo[] running_activities~%~%~%================================================================================~%MSG: activity_msgs/RunningActivityInfo~%string activity_type~%uint64 activity_id~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ListRunningActivitiesResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'running_activities) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ListRunningActivitiesResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ListRunningActivitiesResult
    (cl:cons ':running_activities (running_activities msg))
))
