; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude ListRunningActivitiesGoal.msg.html

(cl:defclass <ListRunningActivitiesGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ListRunningActivitiesGoal (<ListRunningActivitiesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ListRunningActivitiesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ListRunningActivitiesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<ListRunningActivitiesGoal> is deprecated: use activity_msgs-msg:ListRunningActivitiesGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ListRunningActivitiesGoal>) ostream)
  "Serializes a message object of type '<ListRunningActivitiesGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ListRunningActivitiesGoal>) istream)
  "Deserializes a message object of type '<ListRunningActivitiesGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ListRunningActivitiesGoal>)))
  "Returns string type for a message object of type '<ListRunningActivitiesGoal>"
  "activity_msgs/ListRunningActivitiesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ListRunningActivitiesGoal)))
  "Returns string type for a message object of type 'ListRunningActivitiesGoal"
  "activity_msgs/ListRunningActivitiesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ListRunningActivitiesGoal>)))
  "Returns md5sum for a message object of type '<ListRunningActivitiesGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ListRunningActivitiesGoal)))
  "Returns md5sum for a message object of type 'ListRunningActivitiesGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ListRunningActivitiesGoal>)))
  "Returns full string definition for message of type '<ListRunningActivitiesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# empty goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ListRunningActivitiesGoal)))
  "Returns full string definition for message of type 'ListRunningActivitiesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# empty goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ListRunningActivitiesGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ListRunningActivitiesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ListRunningActivitiesGoal
))
