; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StartActivityActionGoal.msg.html

(cl:defclass <StartActivityActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type activity_msgs-msg:StartActivityGoal
    :initform (cl:make-instance 'activity_msgs-msg:StartActivityGoal)))
)

(cl:defclass StartActivityActionGoal (<StartActivityActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartActivityActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartActivityActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StartActivityActionGoal> is deprecated: use activity_msgs-msg:StartActivityActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <StartActivityActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:header-val is deprecated.  Use activity_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <StartActivityActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:goal_id-val is deprecated.  Use activity_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <StartActivityActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:goal-val is deprecated.  Use activity_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartActivityActionGoal>) ostream)
  "Serializes a message object of type '<StartActivityActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartActivityActionGoal>) istream)
  "Deserializes a message object of type '<StartActivityActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartActivityActionGoal>)))
  "Returns string type for a message object of type '<StartActivityActionGoal>"
  "activity_msgs/StartActivityActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartActivityActionGoal)))
  "Returns string type for a message object of type 'StartActivityActionGoal"
  "activity_msgs/StartActivityActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartActivityActionGoal>)))
  "Returns md5sum for a message object of type '<StartActivityActionGoal>"
  "2b410b5afb33365fec52cf1a7567665d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartActivityActionGoal)))
  "Returns md5sum for a message object of type 'StartActivityActionGoal"
  "2b410b5afb33365fec52cf1a7567665d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartActivityActionGoal>)))
  "Returns full string definition for message of type '<StartActivityActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StartActivityGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: activity_msgs/StartActivityGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint64 desired_activity_id~%~%string activity_type~%~%# JSON encoded goal message~%string goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartActivityActionGoal)))
  "Returns full string definition for message of type 'StartActivityActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%StartActivityGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: activity_msgs/StartActivityGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint64 desired_activity_id~%~%string activity_type~%~%# JSON encoded goal message~%string goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartActivityActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartActivityActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StartActivityActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
