; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StartActivityFeedback.msg.html

(cl:defclass <StartActivityFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StartActivityFeedback (<StartActivityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartActivityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartActivityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StartActivityFeedback> is deprecated: use activity_msgs-msg:StartActivityFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartActivityFeedback>) ostream)
  "Serializes a message object of type '<StartActivityFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartActivityFeedback>) istream)
  "Deserializes a message object of type '<StartActivityFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartActivityFeedback>)))
  "Returns string type for a message object of type '<StartActivityFeedback>"
  "activity_msgs/StartActivityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartActivityFeedback)))
  "Returns string type for a message object of type 'StartActivityFeedback"
  "activity_msgs/StartActivityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartActivityFeedback>)))
  "Returns md5sum for a message object of type '<StartActivityFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartActivityFeedback)))
  "Returns md5sum for a message object of type 'StartActivityFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartActivityFeedback>)))
  "Returns full string definition for message of type '<StartActivityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartActivityFeedback)))
  "Returns full string definition for message of type 'StartActivityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartActivityFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartActivityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StartActivityFeedback
))
