; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StartActivityResult.msg.html

(cl:defclass <StartActivityResult> (roslisp-msg-protocol:ros-message)
  ((activity_id
    :reader activity_id
    :initarg :activity_id
    :type cl:integer
    :initform 0)
   (error_code
    :reader error_code
    :initarg :error_code
    :type activity_msgs-msg:ActivityErrorCode
    :initform (cl:make-instance 'activity_msgs-msg:ActivityErrorCode)))
)

(cl:defclass StartActivityResult (<StartActivityResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StartActivityResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StartActivityResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StartActivityResult> is deprecated: use activity_msgs-msg:StartActivityResult instead.")))

(cl:ensure-generic-function 'activity_id-val :lambda-list '(m))
(cl:defmethod activity_id-val ((m <StartActivityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:activity_id-val is deprecated.  Use activity_msgs-msg:activity_id instead.")
  (activity_id m))

(cl:ensure-generic-function 'error_code-val :lambda-list '(m))
(cl:defmethod error_code-val ((m <StartActivityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:error_code-val is deprecated.  Use activity_msgs-msg:error_code instead.")
  (error_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StartActivityResult>) ostream)
  "Serializes a message object of type '<StartActivityResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'activity_id)) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error_code) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StartActivityResult>) istream)
  "Deserializes a message object of type '<StartActivityResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error_code) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StartActivityResult>)))
  "Returns string type for a message object of type '<StartActivityResult>"
  "activity_msgs/StartActivityResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StartActivityResult)))
  "Returns string type for a message object of type 'StartActivityResult"
  "activity_msgs/StartActivityResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StartActivityResult>)))
  "Returns md5sum for a message object of type '<StartActivityResult>"
  "23c7c98855500c7380e4c128ad575c3b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StartActivityResult)))
  "Returns md5sum for a message object of type 'StartActivityResult"
  "23c7c98855500c7380e4c128ad575c3b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StartActivityResult>)))
  "Returns full string definition for message of type '<StartActivityResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# actual id decided on (may be different than the requested~%# id, if that one already existed)~%uint64 activity_id~%~%ActivityErrorCode error_code~%~%~%================================================================================~%MSG: activity_msgs/ActivityErrorCode~%uint8 val~%~%uint8 SUCCESS=0~%uint8 OTHER_ERROR=1~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StartActivityResult)))
  "Returns full string definition for message of type 'StartActivityResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# actual id decided on (may be different than the requested~%# id, if that one already existed)~%uint64 activity_id~%~%ActivityErrorCode error_code~%~%~%================================================================================~%MSG: activity_msgs/ActivityErrorCode~%uint8 val~%~%uint8 SUCCESS=0~%uint8 OTHER_ERROR=1~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StartActivityResult>))
  (cl:+ 0
     8
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error_code))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StartActivityResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StartActivityResult
    (cl:cons ':activity_id (activity_id msg))
    (cl:cons ':error_code (error_code msg))
))
