; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StopActivityFeedback.msg.html

(cl:defclass <StopActivityFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StopActivityFeedback (<StopActivityFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopActivityFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopActivityFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StopActivityFeedback> is deprecated: use activity_msgs-msg:StopActivityFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopActivityFeedback>) ostream)
  "Serializes a message object of type '<StopActivityFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopActivityFeedback>) istream)
  "Deserializes a message object of type '<StopActivityFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopActivityFeedback>)))
  "Returns string type for a message object of type '<StopActivityFeedback>"
  "activity_msgs/StopActivityFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopActivityFeedback)))
  "Returns string type for a message object of type 'StopActivityFeedback"
  "activity_msgs/StopActivityFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopActivityFeedback>)))
  "Returns md5sum for a message object of type '<StopActivityFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopActivityFeedback)))
  "Returns md5sum for a message object of type 'StopActivityFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopActivityFeedback>)))
  "Returns full string definition for message of type '<StopActivityFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopActivityFeedback)))
  "Returns full string definition for message of type 'StopActivityFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopActivityFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopActivityFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StopActivityFeedback
))
