; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StopActivityGoal.msg.html

(cl:defclass <StopActivityGoal> (roslisp-msg-protocol:ros-message)
  ((activity_id
    :reader activity_id
    :initarg :activity_id
    :type cl:integer
    :initform 0))
)

(cl:defclass StopActivityGoal (<StopActivityGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopActivityGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopActivityGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StopActivityGoal> is deprecated: use activity_msgs-msg:StopActivityGoal instead.")))

(cl:ensure-generic-function 'activity_id-val :lambda-list '(m))
(cl:defmethod activity_id-val ((m <StopActivityGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:activity_id-val is deprecated.  Use activity_msgs-msg:activity_id instead.")
  (activity_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopActivityGoal>) ostream)
  "Serializes a message object of type '<StopActivityGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'activity_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'activity_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopActivityGoal>) istream)
  "Deserializes a message object of type '<StopActivityGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'activity_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopActivityGoal>)))
  "Returns string type for a message object of type '<StopActivityGoal>"
  "activity_msgs/StopActivityGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopActivityGoal)))
  "Returns string type for a message object of type 'StopActivityGoal"
  "activity_msgs/StopActivityGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopActivityGoal>)))
  "Returns md5sum for a message object of type '<StopActivityGoal>"
  "c1ae730864c2e4c643bef5d6700095a9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopActivityGoal)))
  "Returns md5sum for a message object of type 'StopActivityGoal"
  "c1ae730864c2e4c643bef5d6700095a9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopActivityGoal>)))
  "Returns full string definition for message of type '<StopActivityGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# id of activity to stop~%uint64 activity_id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopActivityGoal)))
  "Returns full string definition for message of type 'StopActivityGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# id of activity to stop~%uint64 activity_id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopActivityGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopActivityGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StopActivityGoal
    (cl:cons ':activity_id (activity_id msg))
))
