; Auto-generated. Do not edit!


(cl:in-package activity_msgs-msg)


;//! \htmlinclude StopActivityResult.msg.html

(cl:defclass <StopActivityResult> (roslisp-msg-protocol:ros-message)
  ((error_code
    :reader error_code
    :initarg :error_code
    :type activity_msgs-msg:ActivityErrorCode
    :initform (cl:make-instance 'activity_msgs-msg:ActivityErrorCode)))
)

(cl:defclass StopActivityResult (<StopActivityResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StopActivityResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StopActivityResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name activity_msgs-msg:<StopActivityResult> is deprecated: use activity_msgs-msg:StopActivityResult instead.")))

(cl:ensure-generic-function 'error_code-val :lambda-list '(m))
(cl:defmethod error_code-val ((m <StopActivityResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader activity_msgs-msg:error_code-val is deprecated.  Use activity_msgs-msg:error_code instead.")
  (error_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StopActivityResult>) ostream)
  "Serializes a message object of type '<StopActivityResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'error_code) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StopActivityResult>) istream)
  "Deserializes a message object of type '<StopActivityResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'error_code) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StopActivityResult>)))
  "Returns string type for a message object of type '<StopActivityResult>"
  "activity_msgs/StopActivityResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StopActivityResult)))
  "Returns string type for a message object of type 'StopActivityResult"
  "activity_msgs/StopActivityResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StopActivityResult>)))
  "Returns md5sum for a message object of type '<StopActivityResult>"
  "64e09f17a49222b8276a5f3be1ed3597")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StopActivityResult)))
  "Returns md5sum for a message object of type 'StopActivityResult"
  "64e09f17a49222b8276a5f3be1ed3597")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StopActivityResult>)))
  "Returns full string definition for message of type '<StopActivityResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%ActivityErrorCode error_code~%~%~%================================================================================~%MSG: activity_msgs/ActivityErrorCode~%uint8 val~%~%uint8 SUCCESS=0~%uint8 OTHER_ERROR=1~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StopActivityResult)))
  "Returns full string definition for message of type 'StopActivityResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%ActivityErrorCode error_code~%~%~%================================================================================~%MSG: activity_msgs/ActivityErrorCode~%uint8 val~%~%uint8 SUCCESS=0~%uint8 OTHER_ERROR=1~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StopActivityResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'error_code))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StopActivityResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StopActivityResult
    (cl:cons ':error_code (error_code msg))
))
