"""autogenerated by genpy from activity_msgs/ListRunningActivitiesResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import activity_msgs.msg

class ListRunningActivitiesResult(genpy.Message):
  _md5sum = "3611cca087931f599cd9f9c453d0edd4"
  _type = "activity_msgs/ListRunningActivitiesResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

RunningActivityInfo[] running_activities


================================================================================
MSG: activity_msgs/RunningActivityInfo
string activity_type
uint64 activity_id
"""
  __slots__ = ['running_activities']
  _slot_types = ['activity_msgs/RunningActivityInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       running_activities

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ListRunningActivitiesResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.running_activities is None:
        self.running_activities = []
    else:
      self.running_activities = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.running_activities)
      buff.write(_struct_I.pack(length))
      for val1 in self.running_activities:
        _x = val1.activity_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_Q.pack(val1.activity_id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.running_activities is None:
        self.running_activities = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.running_activities = []
      for i in range(0, length):
        val1 = activity_msgs.msg.RunningActivityInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.activity_type = str[start:end].decode('utf-8')
        else:
          val1.activity_type = str[start:end]
        start = end
        end += 8
        (val1.activity_id,) = _struct_Q.unpack(str[start:end])
        self.running_activities.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.running_activities)
      buff.write(_struct_I.pack(length))
      for val1 in self.running_activities:
        _x = val1.activity_type
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_Q.pack(val1.activity_id))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.running_activities is None:
        self.running_activities = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.running_activities = []
      for i in range(0, length):
        val1 = activity_msgs.msg.RunningActivityInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.activity_type = str[start:end].decode('utf-8')
        else:
          val1.activity_type = str[start:end]
        start = end
        end += 8
        (val1.activity_id,) = _struct_Q.unpack(str[start:end])
        self.running_activities.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Q = struct.Struct("<Q")
